### ISSUE TITLE
Unhandled exception when retrieving tags

### ISSUE THREAD

**Issue by AridDay** [StackStorm-Exchange/stackstorm-vsphere#83] opened 2021-04-04 23:33 UTC
It seems that any action to do with retrieving tags gives the following exception. 

Actions that have this exception, that I have found:
tag_id_get
tag_category_list
tag_list
get_objects_with_tag

The following exception was from attempting to run tag_list, but the other actions give a similar exception.

{
  "stdout": "",
  "stderr": "Traceback (most recent call last):
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py\", line 334, in <module>
    obj.run()
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py\", line 193, in run
    output = action.run(**self._parameters)
  File \"/opt/stackstorm/packs/vsphere/actions/tag_list.py\", line 31, in run
    self.connect_rest(kwargs.get(\"vsphere\"))
  File \"/opt/stackstorm/packs/vsphere/actions/vmwarelib/actions.py\", line 118, in connect_rest
    self.tagging.login()
  File \"/opt/stackstorm/packs/vsphere/actions/vmwarelib/tagging.py\", line 131, in login
    return dict(response.cookies)
  File \"/opt/stackstorm/virtualenvs/vsphere/lib/python3.6/site-packages/requests/cookies.py\", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File \"/opt/stackstorm/virtualenvs/vsphere/lib/python3.6/site-packages/requests/cookies.py\", line 394, in _find_no_duplicates
    raise CookieConflictError('There are multiple cookies with name, %r' % (name))
requests.cookies.CookieConflictError: There are multiple cookies with name, 'vmware-api-session-id'
",
  "exit_code": 1,
  "result": "None"
}

**Comment by nmaludy** [comment] 2021-04-05 16:01
@jschoewe any thoughts?

**Comment by jschoewe** [comment] 2021-04-07 21:09
I've never seen this error before and can't seem to replicate it in our environment (vSphere Client version 6.7.0.46000). I'm thinking the issue is because this pack doesn't support python 3 yet. There's an open issue (#79) to get everything updated but we haven't had time to fix it yet.

**Comment by AridDay** [comment] 2021-04-07 22:33
@jschoewe I can also provide more logs if needed. For context, I am pointing it towards vCenter version 7.0.2.00000. 

I'll look into this issue further as well.

**Comment by jschoewe** [comment] 2021-06-30 15:20
Resolving this issue as the tag actions are working again after PR #85

**Closed as completed by jschoewe** 2021-06-30 15:20 UTC
